name = "Minimal2"
license = "MIT"
licenselink = "https://github.com/nathancday/minimal2/blob/master/LICENSE.md"
description = "Personal blog theme powered by Hugo"
homepage = "http://github.com/nathancday/minimal2"
tags = ["blog", "minimal", "personal", "responsive"]
features = ["responsive", "night-theme"]
min_version = "0.24.1"

[author]
  name = "Nate Day"
  homepage = "https://natedayta.com"
